### ISSUE TITLE
Is there any manual for this code?

### ISSUE THREAD

**Issue by mairanteodoro** [barklem/hlinop#1]
Hi,

I'm trying to understand how to use this code. Can you tell me what should I provide as input to the code? What should I do to get the line opacities printed out?

Thank you.

**Comment by barklem** [comment]
Hi,

No, there is no manual beyond the readme and the commenting of the code.  Which code are you trying to use?  Really this is a collection of subroutines, with SYNTH provided as an example of how one could make use of them.

Paul
